### ISSUE TITLE
initdb is failing with regular local sqlite

### ISSUE THREAD

**Issue by dyasny** [wamdam/backy2#12]
/etc/backy.conf:

engine: sqlite:////tml/test.sqlite

#backy2 initdb

    INFO: $ /bin/backy2 initdb
   ERROR: Unexpected exception
   ERROR: (sqlite3.OperationalError) table deleted_blocks already exists [SQL: '\nCREATE TABLE deleted_blocks (\n\tid INTEGER NOT NULL, \n\tuid VARCHAR(32), \n\tsize BIGINT, \n\tdelete_candidate INTEGER NOT NULL, \n\ttime BIGINT NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table deleted_blocks already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/backy2-2.9.17-py3.4.egg/backy2/scripts/backy.py", line 583, in main
    func(**func_args)
  File "/usr/lib/python3.4/site-packages/backy2-2.9.17-py3.4.egg/backy2/scripts/backy.py", line 356, in initdb
    self.backy(initdb=True)
  File "/usr/lib/python3.4/site-packages/backy2-2.9.17-py3.4.egg/backy2/backy.py", line 49, in __init__
    meta_backend.initdb()
  File "/usr/lib/python3.4/site-packages/backy2-2.9.17-py3.4.egg/backy2/meta_backends/sql.py", line 169, in initdb
    Base.metadata.create_all(self.engine, checkfirst=False)  # checkfirst False will raise when it finds an existing table
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/SQLAlchemy-1.2.5-py3.4-linux-x86_64.egg/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table deleted_blocks already exists [SQL: '\nCREATE TABLE deleted_blocks (\n\tid INTEGER NOT NULL, \n\tuid VARCHAR(32), \n\tsize BIGINT, \n\tdelete_candidate INTEGER NOT NULL, \n\ttime BIGINT NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
    INFO: Backy failed.

SELinux disabled, no other errors, sqlite file isn't present and isn't created

**Comment by dyasny** [comment]
This is actually weirder. I checked in /tmp and found backy.sqlite there, deleting this file, initdb ran through fine, but ended up creating backy.sqlite in /tmp again, instead of using the engine: directive from /etc/backy2.cfg

**Comment by dyasny** [comment]
I think I found the problem - if I actually specify -c /etc/backy2.cfg then the config gets picked up, otherwise it is ignored and the db gets created in /tmp.

**Comment by dyasny** [comment]
Found the problem - cfg file has to be backy.cfg not back2.cfg. Closing
