### ISSUE TITLE
Ceph error

### ISSUE THREAD

**Issue by plant75** [wamdam/backy2#4]
Hello,
i have this error:

 backy2 backup rbd://ceph-lxc/vm-100-disk-1@backup1 vm-100-disk-1@backup1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (setproctitle 1.1.8 (/usr/lib/python3/dist-packages), Requirement.parse('setproctitle>=1.1.10'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/backy2", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: setproctitle>=1.1.10
root@n1:~# 

can you help me ?
thanks

**Comment by wamdam** [comment]
Interesting problem. Just closed the other case with this commit.
https://github.com/wamdam/backy2/commit/4c402eb3b0679ccd7b9d3d4153fad81eca7343ae

Please try again with the new code.
