### ISSUE TITLE
how to install backy2 in windows server?

### ISSUE THREAD

**Issue by noeyhuy** [wamdam/backy2#47]
i using windows server 2016 (hyper-v).
how to install backy2 in server? is it the same way as linux?

**Comment by wamdam** [comment]
The more I think about it the more I'm sure that you should be able to just install the deb and its dependencies on ubuntu on windows. Have you tried?

**Comment by noeyhuy** [comment]
yes.. but error occurred ,,,

PS E:\> E:\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py ls
    INFO: $ E:\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py ls
   **ERROR: Invalid database (sqlite:////E:\backy2\backy.sqlite). Please run initdb first.**

PS E:\> **E:\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py initdb**
    INFO: $ E:\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py initdb
   **ERROR: Unexpected exception
   ERROR: (sqlite3.OperationalError) unable to open database file**
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\impl.py", line 238, in _do_get
    return self._create_connection()
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py", line 740, in main
    func(**func_args)
  File "E:\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py", line 459, in initdb
    self.backy(initdb=True)
  File "C:\Python36\lib\site-packages\backy2-2.10.5-py3.6.egg\backy2\backy.py", line 49, in __init__
    meta_backend.initdb()
  File "C:\Python36\lib\site-packages\backy2-2.10.5-py3.6.egg\backy2\meta_backends\sql.py", line 172, in initdb
    Base.metadata.create_all(self.engine, checkfirst=False)  # checkfirst False will raise when it finds an existing table
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\sql\schema.py", line 4316, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\base.py", line 2048, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "C:\Python36\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\base.py", line 2040, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\base.py", line 2242, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\base.py", line 2280, in _wrap_pool_connect
    e, dialect, self
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\base.py", line 1547, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\impl.py", line 238, in _do_get
    return self._create_connection()
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Python36\lib\site-packages\sqlalchemy-1.3.12-py3.6-win-amd64.egg\sqlalchemy\engine\default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)
    INFO: Backy failed.

E:\backy.cfg ↓
engine: sqlite:////E:\backy2\backy.sqlite

**Comment by noeyhuy** [comment]
done
