### ISSUE TITLE
(builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input

### ISSUE THREAD

**Issue by noeyhuy** [wamdam/backy2#48]
i using sqlite. how to fix?

[root@localhost ~]# backy2 backup file:///home/monday/monday.image full_monday
    INFO: $ /usr/local/bin/backy2 backup file:///home/monday/monday.image full_monday
   ERROR: Unexpected exception
   **ERROR: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.**
[SQL: INSERT INTO versions (uid, date, expire, name, snapshot_name, size, size_bytes, valid, protected) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'uid': '1315e2e6-35d8-11ea-86af-52540053aa36', 'size_bytes': 10000000000, 'date': '2020-01-13 07:41:13', 'valid': 0, 'protected': 0, 'name': 'full_monday', 'snapshot_name': '', 'size': 2385, 'expire': None}]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1173, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 799, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/dialects/sqlite/base.py", line 759, in process
    "SQLite DateTime type only accepts Python "
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/backy2-2.10.6-py3.6.egg/backy2/scripts/backy.py", line 740, in main
    func(**func_args)
  File "/usr/local/lib/python3.6/site-packages/backy2-2.10.6-py3.6.egg/backy2/scripts/backy.py", line 95, in backup
    backy.backup(name, snapshot_name, source, hints, from_version, tags, expire_date)
  File "/usr/local/lib/python3.6/site-packages/backy2-2.10.6-py3.6.egg/backy2/backy.py", line 520, in backup
    version_uid = self._prepare_version(name, snapshot_name, source_size, from_version)
  File "/usr/local/lib/python3.6/site-packages/backy2-2.10.6-py3.6.egg/backy2/backy.py", line 79, in _prepare_version
    version_uid = self.meta_backend.set_version(name, snapshot_name, size, size_bytes, 0)
  File "/usr/local/lib/python3.6/site-packages/backy2-2.10.6-py3.6.egg/backy2/meta_backends/sql.py", line 204, in set_version
    self.session.commit()
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1176, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1173, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 799, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.12-py3.6-linux-x86_64.egg/sqlalchemy/dialects/sqlite/base.py", line 759, in process
    "SQLite DateTime type only accepts Python "
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO versions (uid, date, expire, name, snapshot_name, size, size_bytes, valid, protected) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'uid': '1315e2e6-35d8-11ea-86af-52540053aa36', 'size_bytes': 10000000000, 'date': '2020-01-13 07:41:13', 'valid': 0, 'protected': 0, 'name': 'full_monday', 'snapshot_name': '', 'size': 2385, 'expire': None}]]
    INFO: Backy failed.

**Comment by wamdam** [comment]
could you retry with a fresh database? Works here at least with the latest master (which you're using).

**Comment by wamdam** [comment]
As there was no comment within 14 days, I'm closing this ticket now.
