### ISSUE TITLE
Crash when trying to restore to rbd after upgrading ceph cluster

### ISSUE THREAD

**Issue by PeterLinder** [wamdam/backy2#56]
I get the following traceback. Creating the backup works, but if I test a restore, it doesn't work any more.

Tested with 2.9.17 and 2.10.5. How can I help more? Our ceph cluster has been upgraded to 14.2.8.
 
backy2 restore bb45182e-6332-11ea-aa86-0cc47a886a00 rdb://nvme/vm-127-disk-temp
    INFO: $ /usr/bin/backy2 restore bb45182e-6332-11ea-aa86-0cc47a886a00 rdb://nvme/vm-127-disk-temp
   ERROR: Unexpected exception
   ERROR: No module named 'backy2.io.rdb'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 740, in main
    func(**func_args)
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 101, in restore
    backy.restore(version_uid, target, sparse, force)
  File "/usr/lib/python3/dist-packages/backy2/backy.py", line 279, in restore
    io = self.get_io_by_source(target)
  File "/usr/lib/python3/dist-packages/backy2/backy.py", line 155, in get_io_by_source
    IOLib = importlib.import_module('backy2.io.{}'.format(scheme))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'backy2.io.rdb'
    INFO: Backy failed.

**Comment by wamdam** [comment]
Looks like the rbd module is missing. Very strange. Could you reinstall?

**Comment by PeterLinder** [comment]
I did reinstall, twice actually, from the .deb file.

Since creating the backup works (reading rbd) and there has been changes to our ceph cluster I'm thinking that I'm not allowed to write (for some reason) and the error message is somehow wrong. Or what else could be the difference between reading from ceph and writing to it?

**Comment by wamdam** [comment]
Heh, typo. You need to restore to rbd, not rdb.

**Comment by PeterLinder** [comment]
Ahhhh! I will go bury myself now.
