### ISSUE TITLE
(sqlite3.OperationalError) disk I/O error

### ISSUE THREAD

**Issue by noeyhuy** [wamdam/backy2#62]
# disk I/O error how to fix? i using /backup1(/dev/sdb1 mount)  gpt partitions

   Device Boot      Start         End      Blocks   Id  System
/dev/sdb1               1  4294967295  2147483647+  ee  GPT

[root@localhost ~]# cat /backup1/backy2/backup/test/Monday_20200427/backy.log                                                       
2020-04-27 14:50:16,811 [13631] $ /usr/local/bin/backy2 -c /backup1/backy2/backup/test/Monday_20200427/backy.cfg initdb
2020-04-27 14:50:17,132 [13631] Unexpected exception
2020-04-27 14:50:17,133 [13631] (sqlite3.OperationalError) disk I/O error
[SQL: 
CREATE TABLE stats (
        date DATETIME NOT NULL, 
        version_uid VARCHAR(36) NOT NULL, 
        version_name VARCHAR NOT NULL, 
        version_size_bytes BIGINT NOT NULL, 
        version_size_blocks BIGINT NOT NULL, 
        bytes_read BIGINT NOT NULL, 
        blocks_read BIGINT NOT NULL, 
        bytes_written BIGINT NOT NULL, 
        blocks_written BIGINT NOT NULL, 
        bytes_found_dedup BIGINT NOT NULL, 
        blocks_found_dedup BIGINT NOT NULL, 
        bytes_sparse BIGINT NOT NULL, 
        blocks_sparse BIGINT NOT NULL, 
        duration_seconds BIGINT NOT NULL, 
        PRIMARY KEY (version_uid)
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/backy2-2.10.5-py3.6.egg/backy2/scripts/backy.py", line 740, in main
    func(**func_args)
  File "/usr/local/lib/python3.6/site-packages/backy2-2.10.5-py3.6.egg/backy2/scripts/backy.py", line 459, in initdb
    self.backy(initdb=True)
  File "/usr/local/lib/python3.6/site-packages/backy2-2.10.5-py3.6.egg/backy2/backy.py", line 49, in __init__
    meta_backend.initdb()
  File "/usr/local/lib/python3.6/site-packages/backy2-2.10.5-py3.6.egg/backy2/meta_backends/sql.py", line 172, in initdb
    Base.metadata.create_all(self.engine, checkfirst=False)  # checkfirst False will raise when it finds an existing table
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/sql/schema.py", line 4321, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2058, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1627, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 144, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 826, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1046, in _execute_ddl
    compiled,
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/SQLAlchemy-1.3.16-py3.6-linux-x86_64.egg/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error
[SQL: 
CREATE TABLE stats (
        date DATETIME NOT NULL, 
        version_uid VARCHAR(36) NOT NULL, 
        version_name VARCHAR NOT NULL, 
        version_size_bytes BIGINT NOT NULL, 
        version_size_blocks BIGINT NOT NULL, 
        bytes_read BIGINT NOT NULL, 
        blocks_read BIGINT NOT NULL, 
        bytes_written BIGINT NOT NULL, 
        blocks_written BIGINT NOT NULL, 
        bytes_found_dedup BIGINT NOT NULL, 
        blocks_found_dedup BIGINT NOT NULL, 
        bytes_sparse BIGINT NOT NULL, 
        blocks_sparse BIGINT NOT NULL, 
        duration_seconds BIGINT NOT NULL, 
        PRIMARY KEY (version_uid)
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)
2020-04-27 14:50:17,135 [13631] Backy failed.

**Comment by noeyhuy** [comment]
fix it
