### ISSUE TITLE
list index out of range!!!!!

### ISSUE THREAD

**Issue by noeyhuy** [wamdam/backy2#64]
**# rm success**
PS C:\> C:\Python36\python.exe E:\backy2\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py -c E:\backy2\backy2-2.10.5\backy2-2.10.5\etc\backy.cfg rm -f 35ac9c14-8f69-11ea-9eaa-782bcb439d11
    INFO: $ E:\backy2\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py -c E:\backy2\backy2-2.10.5\backy2-2.10.5\etc\backy.cfg rm -f 35ac9c14-8f69-11ea-9eaa-782bcb439d11
    INFO: Removed backup version 35ac9c14-8f69-11ea-9eaa-782bcb439d11 with 1809 blocks.
    INFO: Backy complete.

**# cleanup failed**
PS C:\> C:\Python36\python.exe E:\backy2\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py -c E:\backy2\backy2-2.10.5\backy2-2.10.5\etc\backy.cfg cleanup --full
    INFO: $ E:\backy2\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py -c E:\backy2\backy2-2.10.5\backy2-2.10.5\etc\backy.cfg cleanup --full
   ERROR: Unexpected exception
   ERROR: list index out of range
Traceback (most recent call last):
  File "E:\backy2\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py", line 740, in main
    func(**func_args)
  File "E:\backy2\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py", line 297, in cleanup
    backy.cleanup_full(prefix)
  File "C:\Python36\lib\site-packages\backy2-2.10.5-py3.6.egg\backy2\backy.py", line 689, in cleanup_full
    if len(find_other_procs(self.process_name)) > 1:
  File "C:\Python36\lib\site-packages\backy2-2.10.5-py3.6.egg\backy2\locking.py", line 60, in find_other_procs
    return [p for p in psutil.process_iter() if p.name().split()[0] == name]
  File "C:\Python36\lib\site-packages\backy2-2.10.5-py3.6.egg\backy2\locking.py", line 60, in <listcomp>
    return [p for p in psutil.process_iter() if p.name().split()[0] == name]
IndexError: list index out of range
    INFO: Backy failed.

PS C:\> C:\Python36\python.exe E:\backy2\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py -c E:\backy2\backy2-2.10.5\backy2-2.10.5\etc\backy.cfg cleanup --full --prefix=a
    INFO: $ E:\backy2\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py -c E:\backy2\backy2-2.10.5\backy2-2.10.5\etc\backy.cfg cleanup --full --prefix=a
   ERROR: Unexpected exception
   ERROR: list index out of range
Traceback (most recent call last):
  File "E:\backy2\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py", line 740, in main
    func(**func_args)
  File "E:\backy2\backy2-2.10.5\backy2-2.10.5\src\backy2\scripts\backy.py", line 297, in cleanup
    backy.cleanup_full(prefix)
  File "C:\Python36\lib\site-packages\backy2-2.10.5-py3.6.egg\backy2\backy.py", line 689, in cleanup_full
    if len(find_other_procs(self.process_name)) > 1:
  File "C:\Python36\lib\site-packages\backy2-2.10.5-py3.6.egg\backy2\locking.py", line 60, in find_other_procs
    return [p for p in psutil.process_iter() if p.name().split()[0] == name]
  File "C:\Python36\lib\site-packages\backy2-2.10.5-py3.6.egg\backy2\locking.py", line 60, in <listcomp>
    return [p for p in psutil.process_iter() if p.name().split()[0] == name]
IndexError: list index out of range
    INFO: Backy failed.

**# how to fix?**

**Comment by noeyhuy** [comment]
fix it
