### ISSUE TITLE
backy2 not running anymore after upgrade

### ISSUE THREAD

**Issue by SSchneebeli** [wamdam/backy2#66]
Hi

I upgraded backy2 form 2.10.5 to 2.12.4. I reconfigured the DB (PostgreSQL) and the DataBackend as it was set before. I created a new encryption key as backy2 wanted to have to set one even the encryption_version is set to 0. But still backy2 won't run anymore because of the Crypto Module and DataBackend is not supported:

    INFO: $ /usr/bin/backy2 ls
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/backy2/utils.py", line 114, in backy_from_config
    DataBackendLib = importlib.import_module(config_DataBackend.get('type'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/backy2/data_backends/__init__.py", line 7, in <module>
    from backy2.crypt import get_crypt
  File "/usr/lib/python3/dist-packages/backy2/crypt.py", line 1, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/backy2", line 11, in <module>
    load_entry_point('backy2==2.12.4', 'console_scripts', 'backy2')()
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 734, in main
    commands = Commands(args.machine_output, args.skip_header, args.human_readable, Config)
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 31, in __init__
    self.backy = backy_from_config(Config)
  File "/usr/lib/python3/dist-packages/backy2/utils.py", line 116, in backy_from_config
    raise NotImplementedError('DataBackend type {} unsupported.'.format(config_DataBackend.get('type')))
NotImplementedError: DataBackend type backy2.data_backends.file unsupported.

I dind't change this line:
type: backy2.data_backends.file

The Server is running Ubuntu 18.04

Any idea what's wrong?
Thanks!

**Comment by rjhenry** [comment]
I'm seeing the same with a backup to S3 (still using the Boto library, not MinIO):
```
    INFO: $ /usr/bin/backy2 ls
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/backy2/utils.py", line 114, in backy_from_config
    DataBackendLib = importlib.import_module(config_DataBackend.get('type'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/backy2/data_backends/__init__.py", line 7, in <module>
    from backy2.crypt import get_crypt
  File "/usr/lib/python3/dist-packages/backy2/crypt.py", line 1, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/backy2", line 11, in <module>
    load_entry_point('backy2==2.12.4', 'console_scripts', 'backy2')()
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 734, in main
    commands = Commands(args.machine_output, args.skip_header, args.human_readable, Config)
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 31, in __init__
    self.backy = backy_from_config(Config)
  File "/usr/lib/python3/dist-packages/backy2/utils.py", line 116, in backy_from_config
    raise NotImplementedError('DataBackend type {} unsupported.'.format(config_DataBackend.get('type')))
NotImplementedError: DataBackend type backy2.data_backends.s3 unsupported.
```
I haven't changed the data_backend configuration section.

**Comment by rjhenry** [comment]
Hi @SSchneebeli 

I found that installing the Debian package `python3-crypto` helped with this - you might find something similar.

**Comment by SSchneebeli** [comment]
Hi rjhenry

That worked for me too but I had also to install python3-fusepy, python3-lz4 and python3-pycryptodome
So to get it working it was `apt install python3-fusepy python3-lz4 python3-pycryptodome python3-crypto`

Thank you for the hint!
