### ISSUE TITLE
backy2 commands fail if encryption_key is not set even if encryption_version is 0

### ISSUE THREAD

**Issue by gschoenberger** [wamdam/backy2#67]
We started our new backup server with the latest backy2 version and right after start we had the problem that our backy config was not correct.
We want to disable encryption, here is our backy config and as you can see encryption_version is set to 0:
```
[DEFAULTS]
logfile: /home/testubuntu2004_home/backy2.log
block_size: 4194304
hash_function: sha512
lock_dir: /home/testubuntu2004_home
process_name: backy2_testubuntu2004_home
disallow_rm_when_younger_than_days: 6
encryption_version: 0

[MetaBackend]
type: backy2.meta_backends.sql
engine: postgresql://backy2:XXXXXXXXXX@localhost/testubuntu2004_home

[DataBackend]
simultaneous_writes: 5
type: backy2.data_backends.file
path: /home/testubuntu2004_home

[NBD]
cachedir: /home/testubuntu2004_home

[io_rbd]
ceph_conffile: /etc/ceph/ceph.conf
new_image_features:
    RBD_FEATURE_LAYERING
    RBD_FEATURE_EXCLUSIVE_LOCK
    RBD_FEATURE_OBJECT_MAP
    RBD_FEATURE_FAST_DIFF
    RBD_FEATURE_DEEP_FLATTEN
```
If we then try to run backy2 commands an exception occurs:
```
# /usr/bin/backy2 -c /etc/backy2/testubuntu2004_home.cfg initdb
    INFO: [backy2.logging] $ /usr/bin/backy2 -c /etc/backy2/testubuntu2004_home.cfg initdb
Traceback (most recent call last):
  File "/usr/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.8/collections/__init__.py", line 891, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 883, in __missing__
    raise KeyError(key)
KeyError: 'encryption_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/backy2", line 11, in <module>
    load_entry_point('backy2==2.12.5', 'console_scripts', 'backy2')()
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 741, in main
    commands = Commands(args.machine_output, args.skip_header, args.human_readable, Config)
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 31, in __init__
    self.backy = backy_from_config(Config)
  File "/usr/lib/python3/dist-packages/backy2/utils.py", line 96, in backy_from_config
    encryption_key = config_DEFAULTS.get('encryption_key', None)  # if None then version=0 will be used (no encryption)
  File "/usr/lib/python3/dist-packages/backy2/config.py", line 81, in get
    return self._getany(self.cp.get, option, default)
  File "/usr/lib/python3/dist-packages/backy2/config.py", line 74, in _getany
    return method(self.SECTION, option)
  File "/usr/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'encryption_key' in section: 'DEFAULTS'
```
Shouldn't it be possible to unset the key in the config if the encryption_version is 0?

**Comment by wamdam** [comment]
Correct. Should be fixed with 4cdb24069823e1861656673663a987c0f43e155b. Can you confirm?

**Comment by gschoenberger** [comment]
Works as expected! Will the fix be included in the next release?
THX, Georg

**Comment by wamdam** [comment]
Thanks for testing. Yes, this will be in the next release (and is even in master now). Do you need a new release including the fix?

**Comment by gschoenberger** [comment]
Currently I modified the source, so no need for a new release IMO.
