### ISSUE TITLE
backy2 differential backup fails with segmentation fault

### ISSUE THREAD

**Issue by gschoenberger** [wamdam/backy2#73]
Today morning was the second time I have got a segmentation fault while running a backy2 differential backup.
I don't know if the fault is directly related to backy, it could a problem in librbd or a ceph library also.

Maybe someone can point me in the right direction with all the debug output I am providing below?

Current ceph/librbd version:
ii  ceph-common                          15.2.3-1focal
from: 
deb http://download.ceph.com/debian-octopus focal main

There is already 15.2.4-1focal and we plan to update soon. Maybe this includes fixes for the occurring segmentation fault. 

Last log lines from backy output:
```
    INFO: [backy2.logging] Backing up (2/2: Data) rbd://cephstorage/server_system@b_daily_2020-09-06T01:36:37 Read Queue [==========] Write Queue [          ] (98.4% 26.9MB/sØ ETA 1s) 
    INFO: [backy2.logging] New version: a6fd2912-efd0-11ea-94a9-392a179ed511 (Tags: [b_daily])
    INFO: [backy2.logging] Backy complete.

run_backy_backups.sh: line 575: 2550725 Segmentation fault      (core dumped) "$BACKY_BIN" -c "$backy_cfg" backup --tag "$snap_prefix" --expire "$expire_date" --snapshot-name "$snap_name" --rbd "$tmp_file" --from-version "$backy_snap_uid" rbd://"$pool_partition"@"$snap_name" "$partition"
```
Head from apport crash:
```
ProblemType: Crash
Architecture: amd64
Date: Sun Sep  6 01:37:43 2020
DistroRelease: Ubuntu 20.04
ExecutablePath: /usr/bin/python3.8
ExecutableTimestamp: 1588002814
Package: 0
ProcCmdline: backy2_server_system\ [Backing\ up\ (2/2:\ Data)\ rbd://cephstorage/server_system@b_daily_2020-09-06T01:36:37\ Read\ Queue\ [==========]\ Write\ Queue\ [\ \ \ \ \ \ \ \ \ \ ]\ (98.4%\ 26.9MB/sØ\ ETA\ 1s)\ ]
ProcCwd: /root
```

Backtrace from core dump:
```
#0  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:868
#1  0x00007f764b6fb2f8 in std::_Rb_tree<std::basic_string_view<char, std::char_traits<char> >, std::pair<std::basic_string_view<char, std::char_traits<char> > const, Option const&>, std::_Select1st<std::pair<std::basic_string_view<char, std::char_traits<char> > const, Option const&> >, std::less<std::basic_string_view<char, std::char_traits<char> > >, std::allocator<std::pair<std::basic_string_view<char, std::char_traits<char> > const, Option const&> > >::find(std::basic_string_view<char, std::char_traits<char> > const&) const () from /usr/lib/ceph/libceph-common.so.2
#2  0x00007f764b7224a5 in md_config_t::find_option(std::basic_string_view<char, std::char_traits<char> >) const () from /usr/lib/ceph/libceph-common.so.2
#3  0x00007f764b726ae0 in md_config_t::_get_val(ConfigValues const&, std::basic_string_view<char, std::char_traits<char> >, boost::container::small_vector<std::pair<Option const*, boost::variant<boost::blank, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, long, double, bool, entity_addr_t, entity_addrvec_t, std::chrono::duration<long, std::ratio<1l, 1l> >, Option::size_t, uuid_d> const*>, 4ul, void, void>*, std::ostream*) const ()
   from /usr/lib/ceph/libceph-common.so.2
#4  0x00007f764b726e97 in md_config_t::get_val_generic[abi:cxx11](ConfigValues const&, std::basic_string_view<char, std::char_traits<char> >) const ()
   from /usr/lib/ceph/libceph-common.so.2
#5  0x00007f764b968064 in MonClient::_un_backoff() () from /usr/lib/ceph/libceph-common.so.2
#6  0x00007f764b9784a0 in MonClient::tick() () from /usr/lib/ceph/libceph-common.so.2
#7  0x00007f764b64430d in Context::complete(int) () from /usr/lib/ceph/libceph-common.so.2
#8  0x00007f764b6a4deb in SafeTimer::timer_thread() () from /usr/lib/ceph/libceph-common.so.2
#9  0x00007f764b6a6291 in SafeTimerThread::entry() () from /usr/lib/ceph/libceph-common.so.2
#10 0x00007f767889f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007f76789db103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by wamdam** [comment]
Hi,
thanks for the report, however I have not been able to reproduce this. It seems this is somewhere inside libs on your system (libceph) where there might be some incompatibility. I'll close this issue for now as nobody else has had this problem and I'm unable to debug it further.
