### ISSUE TITLE
Infomation debug Ubuntu18.04 

### ISSUE THREAD

**Issue by uncelvel** [wamdam/backy2#75]
I have some issue for backy2 2020-10-06

Env
- backy2_2.13.2_all.deb
- OS: Ubuntu 18.04.5 LTS
- Using S3 minio connection 

Issue
- Backup OK but status when backup is much more infomation like debug mode 

```
Message: 'Backing up (2/2: Data) rbd://ceph/vm-102-disk-0 Read Queue [==========] Write Queue [          ] (94.3% 105.5MB/s\xd8 ETA 11s) '
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xd8' in position 140: ordinal not in range(128)
Call stack:
  File "/usr/bin/backy2", line 11, in <module>
    load_entry_point('backy2==2.13.2', 'console_scripts', 'backy2')()
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 757, in main
    func(**func_args)
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 95, in backup
    version_uid = backy.backup(name, snapshot_name, source, hints, from_version, tags, expire_date, continue_version, output_version_uid_early=self.machine_output)
  File "/usr/lib/python3/dist-packages/backy2/backy.py", line 946, in backup
    logger.info(_status)
Message: 'Backing up (2/2: Data) rbd://ceph/vm-102-disk-0 Read Queue [==========] Write Queue [          ] (97.4% 108.3MB/s\xd8 ETA 5s) '
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xd8' in position 144: ordinal not in range(128)
Call stack:
  File "/usr/bin/backy2", line 11, in <module>
    load_entry_point('backy2==2.13.2', 'console_scripts', 'backy2')()
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 757, in main
    func(**func_args)
  File "/usr/lib/python3/dist-packages/backy2/scripts/backy.py", line 95, in backup
    version_uid = backy.backup(name, snapshot_name, source, hints, from_version, tags, expire_date, continue_version, output_version_uid_early=self.machine_output)
  File "/usr/lib/python3/dist-packages/backy2/backy.py", line 946, in backup
    logger.info(_status)
Message: 'Backing up (2/2: Data) rbd://ceph/vm-102-disk-0 Read Queue [==========] Write Queue [          ] (97.4% 108.3MB/s\xd8 ETA 5s) '
Arguments: ()
    INFO: [backy2.logging] New version: 57589c72-07b1-11eb-a31e-525400838970 (Tags: [weekly_41])
    INFO: [backy2.logging] Backy complete.
```
This is my volume info 
```sh 
root@backup-ods:~# backy2 ls
    INFO: [backy2.logging] $ /usr/bin/backy2 ls
+---------------------+---------------+---------------+------+-------------+--------------------------------------+-------+-----------+-----------+--------+
|         date        | name          | snapshot_name | size |  size_bytes |                 uid                  | valid | protected | tags      | expire |
+---------------------+---------------+---------------+------+-------------+--------------------------------------+-------+-----------+-----------+--------+
| 2020-10-06 08:53:02 | vm-102-disk-0 |               | 5120 | 21474836480 | 57589c72-07b1-11eb-a31e-525400838970 |   1   |     0     | weekly_41 |        |
+---------------------+---------------+---------------+------+-------------+--------------------------------------+-------+-----------+-----------+--------+
    INFO: [backy2.logging] Backy complete.

root@backup-ods:~# 
```
Any suggestion for this, many thank 

Update: When i change OS Ubuntu20.04 everythings is normally 
```sh 
    INFO: [backy2.logging] Backing up (2/2: Data) rbd://ceph/vm-102-disk-0 Read Queue [==========] Write Queue [          ] (89.0% 101.6MB/sØ ETA 22s) 
    INFO: [backy2.logging] Backing up (2/2: Data) rbd://ceph/vm-102-disk-0 Read Queue [==========] Write Queue [          ] (92.9% 105.3MB/sØ ETA 14s) 
    INFO: [backy2.logging] Backing up (2/2: Data) rbd://ceph/vm-102-disk-0 Read Queue [==========] Write Queue [          ] (96.6% 109.0MB/sØ ETA 6s) 
    INFO: [backy2.logging] New version: 0cf1900e-0846-11eb-aab7-cd98b64519b5 (Tags: [weekly_41])
    INFO: [backy2.logging] Backy complete.

root@backup-ods:~# 
```

**Comment by wamdam** [comment]
This is the 'Ø' character. Seems you don't have a utf-8 console on 18.04 or you have changed the default encoding of your python installation?

**Comment by wamdam** [comment]
no reply
